[package]
name = "CrossChainSwap"
version = "1.0.0"
authors = ["1inch"]

[addresses]
bridge = "_"

[dev-addresses]
bridge = "0xCAFE"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "mainnet" }

[dev-dependencies]
