name:                 cardano-cross-chain-swap
version:              0.1.0.0
visibility:           public
id:                   cardano-cross-chain-swap-0.1.0.0-inplace
key:                  cardano-cross-chain-swap-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      CardanoEscrow CardanoResolver
import-dirs:
    /Users/ankush/Developer/1inch-example/cardano-contracts/dist-newstyle/build/aarch64-osx/ghc-9.12.2/cardano-cross-chain-swap-0.1.0.0/build

library-dirs:
    /Users/ankush/Developer/1inch-example/cardano-contracts/dist-newstyle/build/aarch64-osx/ghc-9.12.2/cardano-cross-chain-swap-0.1.0.0/build

library-dirs-static:
    /Users/ankush/Developer/1inch-example/cardano-contracts/dist-newstyle/build/aarch64-osx/ghc-9.12.2/cardano-cross-chain-swap-0.1.0.0/build

dynamic-library-dirs:
    /Users/ankush/Developer/1inch-example/cardano-contracts/dist-newstyle/build/aarch64-osx/ghc-9.12.2/cardano-cross-chain-swap-0.1.0.0/build

data-dir:             /Users/ankush/Developer/1inch-example/cardano-contracts/.
hs-libraries:         HScardano-cross-chain-swap-0.1.0.0-inplace
depends:
    sn-2.2.3.0-7dac99b3 base-4.21.0.0-inplace
    bytestring-0.12.2.0-inplace text-2.1.2-inplace

haddock-interfaces:
    /Users/ankush/Developer/1inch-example/cardano-contracts/dist-newstyle/build/aarch64-osx/ghc-9.12.2/cardano-cross-chain-swap-0.1.0.0/doc/html/cardano-cross-chain-swap/cardano-cross-chain-swap.haddock

haddock-html:
    /Users/ankush/Developer/1inch-example/cardano-contracts/dist-newstyle/build/aarch64-osx/ghc-9.12.2/cardano-cross-chain-swap-0.1.0.0/doc/html/cardano-cross-chain-swap
